---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Filesystem
      - id: check-case-conflict
      - id: check-symlinks
      # Whitespace
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # Syntax
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.14.1
    hooks:
      - id: stylua
